[package]
name = "smart_home_tcp_client"
version = "0.1.0"
edition = "2021"

[dependencies]
smart_home_api = { version = "0.1.0", path = "../smart_home_api" }
serde = { version = "1.0.214", features = ["derive"]}
serde_json = "1.0.132"
